### PR TITLE
Tom - Added template literal examples

### PR DESCRIPTION
**Pull request by tomLendy**
- Added template literal examples.

### CODE REVIEW

**Comment by tomLendy** [comment]
Well darn. Looks like the linting failed. 👎

**Comment by matt-jarrett** [comment]
I like the idea of showing multi line. It also shows the ability to avoid escaping quotes. Can we add a simple one line example to not be so complicated in the example?

Thoughts?

**Comment by tomLendy** [comment]
@matt-jarrett Sure thing. I will work on that and get back to you.

**Comment by matt-jarrett** [comment]
Hey @tomLendy - I liked your idea of adding multiline so I added it in #4 . I didn't add a escape example because it's not a feature unique to Template Literals. You can get out of headaches with other options like single quotes. I'll close this, but feel free to continue the discussion.

`const phrase = 'Joe said, "Hello Lisa."'`

Let me know if you have any feedback?

As for Travis CI, it's rad. I can show you around it if you want 😃 It's easy and pretty straight forward.

**Comment by tomLendy** [comment]
Thanks, I was pretty busy this weekend so I didn't get much done on Git
until a bit ago.

I finished the angular tutorial. Interesting thing about that is when you
run the "ng serve -o" command through git it messes with your git console.
So going back to use git gui is difficult.

When I added the escape examples my intent was to show how difficult they
can be. Then seeing the same examples in template literals would really
illustrate how awesome they are. One of those examples wasn't able to use
just alternating quotes because it included contractions. For example
"can't" was a part of the quoted text. That really screwed things up and
needed both alternating quotes and escapes.

Catch you tomorrow. Well chat about Tyler CI then. Thanks.

**Pull request closed without merging**
